repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Import Formatter (isort)
        stages: ["commit"]
        files: ".py"

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: Python Formatter (Black)
        stages: ["commit"]
        files: ".py"
        args: ["--line-length", "120"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Linter (Flake8)
        stages: ["commit"]
        files: ".py"
        args: ["--config=.flake8"]
